-- =========================================================================
--  CREATE USERS TABLE
-- =========================================================================
CREATE TABLE users (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255),
                       email VARCHAR(255),
                       password VARCHAR(255),
                       role VARCHAR(255), -- Managed by EnumType.STRING in Java
                       last_login TIMESTAMP(6) WITHOUT TIME ZONE
);

-- =========================================================================
--  CREATE ATTENDANCE TABLE
-- =========================================================================
CREATE TABLE attendance (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id INTEGER,
                            check_in_time TIMESTAMP(6) WITHOUT TIME ZONE,
                            check_out_time TIMESTAMP(6) WITHOUT TIME ZONE,
                            total_work_min INTEGER NOT NULL,
                            attendance_status VARCHAR(255), -- Maps to @Column(name = "attendance_status")
                            overtime INTEGER NOT NULL,
                            undertime INTEGER NOT NULL,
                            CONSTRAINT fk_attendance_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =========================================================================
--  CREATE TASKS TABLE
-- =========================================================================
CREATE TABLE tasks (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       description TEXT, -- Maps to columnDefinition = "TEXT"
                       duration_mins INTEGER NOT NULL, -- Maps to @Column(name = "duration_mins")
                       created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, -- Managed by @PrePersist in Java
                       user_id INTEGER NOT NULL,
                       attendance_id INTEGER NOT NULL,
                       CONSTRAINT fk_tasks_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                       CONSTRAINT fk_tasks_attendance FOREIGN KEY (attendance_id) REFERENCES attendance(id) ON DELETE CASCADE
);