
# APPLICATION PROPERTIES

spring.application.name=${SPRING.APPLICATION.NAME}

# Database URL
spring.datasource.url=${POSTGRES.URL}

# PostgreSQL credentials
spring.datasource.username=${POSTGRES.USER}
spring.datasource.password=${POSTGRES.PASSWORD}

# Hibernate settings
# 'update' automatically creates/updates tables based on your Entities
spring.jpa.hibernate.ddl-auto=update

# Show the SQL queries in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG

spring.security.user.name=${SPRING.SECURITY.USER}
spring.security.user.password=${SPRING.SECURITY.PASSWORD}
